-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 22:12:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema McFit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema McFit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `McFit` DEFAULT CHARACTER SET utf8 ;
USE `McFit` ;

-- -----------------------------------------------------
-- Table `McFit`.`GIMNASIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`GIMNASIO` ;

CREATE TABLE IF NOT EXISTS `McFit`.`GIMNASIO` (
  `idGIMNASIO` INT NOT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idGIMNASIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`ZONA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`ZONA` ;

CREATE TABLE IF NOT EXISTS `McFit`.`ZONA` (
  `idZona` INT NOT NULL,
  `color` VARCHAR(45) NULL DEFAULT NULL,
  `GIMNASIO_idGIMNASIO` INT NOT NULL,
  PRIMARY KEY (`idZona`, `GIMNASIO_idGIMNASIO`),
  INDEX `fk_ZONA_GIMNASIO1_idx` (`GIMNASIO_idGIMNASIO` ASC) VISIBLE,
  CONSTRAINT `fk_ZONA_GIMNASIO1`
    FOREIGN KEY (`GIMNASIO_idGIMNASIO`)
    REFERENCES `McFit`.`GIMNASIO` (`idGIMNASIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`MAQUINAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`MAQUINAS` ;

CREATE TABLE IF NOT EXISTS `McFit`.`MAQUINAS` (
  `numeroDeSerie` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `ZONA_idZona` INT NOT NULL,
  PRIMARY KEY (`numeroDeSerie`),
  INDEX `fk_MAQUINAS_ZONA_idx` (`ZONA_idZona` ASC) VISIBLE,
  CONSTRAINT `fk_MAQUINAS_ZONA`
    FOREIGN KEY (`ZONA_idZona`)
    REFERENCES `McFit`.`ZONA` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`SOCIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`SOCIO` ;

CREATE TABLE IF NOT EXISTS `McFit`.`SOCIO` (
  `idSOCIO` INT NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `dni` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `mail` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `GIMNASIO_idGIMNASIO` INT NOT NULL,
  PRIMARY KEY (`idSOCIO`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) VISIBLE,
  INDEX `fk_SOCIO_GIMNASIO1_idx` (`GIMNASIO_idGIMNASIO` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  CONSTRAINT `fk_SOCIO_GIMNASIO1`
    FOREIGN KEY (`GIMNASIO_idGIMNASIO`)
    REFERENCES `McFit`.`GIMNASIO` (`idGIMNASIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`VENTAS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`VENTAS` ;

CREATE TABLE IF NOT EXISTS `McFit`.`VENTAS` (
  `idVENTAS` INT NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `SOCIO_idSOCIO` INT NOT NULL,
  PRIMARY KEY (`idVENTAS`),
  INDEX `fk_VENTAS_SOCIO1_idx` (`SOCIO_idSOCIO` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_SOCIO1`
    FOREIGN KEY (`SOCIO_idSOCIO`)
    REFERENCES `McFit`.`SOCIO` (`idSOCIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`PRODUCTO` ;

CREATE TABLE IF NOT EXISTS `McFit`.`PRODUCTO` (
  `idPRODUCTO` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `precio` DECIMAL NULL DEFAULT NULL,
  `stock` VARCHAR(45) NULL,
  PRIMARY KEY (`idPRODUCTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`EMPLEADO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`EMPLEADO` ;

CREATE TABLE IF NOT EXISTS `McFit`.`EMPLEADO` (
  `idEmpleado` INT NOT NULL,
  `dni` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `tipoEmpelado` VARCHAR(45) NULL DEFAULT NULL,
  `GIMNASIO_idGIMNASIO` INT NOT NULL,
  `idJefe` INT NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  INDEX `fk_EMPLEADO_GIMNASIO1_idx` (`GIMNASIO_idGIMNASIO` ASC) VISIBLE,
  INDEX `fk_EMPLEADO_EMPLEADO1_idx` (`idJefe` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_GIMNASIO1`
    FOREIGN KEY (`GIMNASIO_idGIMNASIO`)
    REFERENCES `McFit`.`GIMNASIO` (`idGIMNASIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_EMPLEADO1`
    FOREIGN KEY (`idJefe`)
    REFERENCES `McFit`.`EMPLEADO` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`PEDIDO` ;

CREATE TABLE IF NOT EXISTS `McFit`.`PEDIDO` (
  `idPedido` INT NOT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  `EMPLEADO_idEmpleado` INT NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_PEDIDO_EMPLEADO1_idx` (`EMPLEADO_idEmpleado` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_EMPLEADO1`
    FOREIGN KEY (`EMPLEADO_idEmpleado`)
    REFERENCES `McFit`.`EMPLEADO` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`DETALLE_VENTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`DETALLE_VENTA` ;

CREATE TABLE IF NOT EXISTS `McFit`.`DETALLE_VENTA` (
  `VENTAS_idVENTAS` INT NOT NULL,
  `PRODUCTO_idPRODUCTO` INT NOT NULL,
  `cantProducto` INT NULL DEFAULT NULL,
  PRIMARY KEY (`VENTAS_idVENTAS`, `PRODUCTO_idPRODUCTO`),
  INDEX `fk_VENTAS_has_PRODUCTO_PRODUCTO1_idx` (`PRODUCTO_idPRODUCTO` ASC) VISIBLE,
  INDEX `fk_VENTAS_has_PRODUCTO_VENTAS1_idx` (`VENTAS_idVENTAS` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_has_PRODUCTO_VENTAS1`
    FOREIGN KEY (`VENTAS_idVENTAS`)
    REFERENCES `McFit`.`VENTAS` (`idVENTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_has_PRODUCTO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_idPRODUCTO`)
    REFERENCES `McFit`.`PRODUCTO` (`idPRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `McFit`.`DETALLE_PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `McFit`.`DETALLE_PEDIDO` ;

CREATE TABLE IF NOT EXISTS `McFit`.`DETALLE_PEDIDO` (
  `PRODUCTO_idPRODUCTO` INT NOT NULL,
  `PEDIDO_idPedido` INT NOT NULL,
  `cantProducto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`PRODUCTO_idPRODUCTO`, `PEDIDO_idPedido`),
  INDEX `fk_PRODUCTO_has_PEDIDO_PEDIDO1_idx` (`PEDIDO_idPedido` ASC) VISIBLE,
  INDEX `fk_PRODUCTO_has_PEDIDO_PRODUCTO1_idx` (`PRODUCTO_idPRODUCTO` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PRODUCTO1`
    FOREIGN KEY (`PRODUCTO_idPRODUCTO`)
    REFERENCES `McFit`.`PRODUCTO` (`idPRODUCTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUCTO_has_PEDIDO_PEDIDO1`
    FOREIGN KEY (`PEDIDO_idPedido`)
    REFERENCES `McFit`.`PEDIDO` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
